const languages = [
  { name: "Arabic", id: 1 },
  { name: "Cantonese", id: 2 },
  { name: "Czech", id: 3 },
  { name: "Danish", id: 4 },
  { name: "Dutch", id: 5 },
  { name: "English", id: 6 },
  { name: "French", id: 7 },
  { name: "German", id: 8 },
  { name: "Hebrew", id: 9 },
  { name: "Hindi", id: 10 },
  { name: "Italian", id: 11 },
  { name: "Japanese", id: 12 },
  { name: "Korean", id: 13 },
  { name: "Malayalam", id: 14 },
  { name: "Mandarin", id: 15 },
  { name: "Norwegian", id: 16 },
  { name: "Polish", id: 17 },
  { name: "Portuguese", id: 18 },
  { name: "Punjabi", id: 19 },
  { name: "Romanian", id: 20 },
  { name: "Russian", id: 21 },
  { name: "Spanish", id: 22 },
  { name: "Swedish", id: 23 },
  { name: "Tamil", id: 24 },
  { name: "Telugu", id: 25 },
  { name: "Turkish", id: 26 },
];

const getLanguage = () => {
  return [
    "English",
    "French",
    "Spanish",
    "Mandarin",
    "Italian",
    "Japanese",
    "Korean",
    "German",
    "Russian",
    "Hindi",
    "Turkish",
    "Portuguese",
    "Arabic",
    "Tamil",
    "Dutch",
    "Cantonese",
    "Telugu",
    "Polish",
    "Czech",
    "Punjabi",
    "Hebrew",
    "Malayalam",
    "Swedish",
    "Danish",
    "Romanian",
    "Norwegian",
  ];
};
module.exports = {
  getLanguage,
};
